### PR TITLE
Better revisions

### PR DESCRIPTION
**Pull request by idlefingers**
Making revisions include url and published attributes so that you can make a project change a Page's status rather than having url changes happening on live pages all the time.

### CODE REVIEW

**Comment by idlefingers** [comment]
@marreman

**Comment by marreman** [comment]
Nice! Does this include page deletion as well? Does that happen on a per revision basis?

**Review by marreman — APPROVED** [review]
:ring:

**Comment by idlefingers** [comment]
Page deletion is still on the higher, container-level. Will look into moving that onto revisions later, perhaps.

**Pull request merged**
